<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" total="1" passed="0">
  <reporter-output>
  </reporter-output>
  <suite name="Suite" duration-ms="145849" started-at="2020-10-30T16:50:38Z" finished-at="2020-10-30T16:53:04Z">
    <groups>
    </groups>
    <test name="Test" duration-ms="145849" started-at="2020-10-30T16:50:38Z" finished-at="2020-10-30T16:53:04Z">
      <class name="TestCases.Amazon">
        <test-method status="PASS" signature="setUp()[pri:0, instance:TestCases.Amazon@2781e022]" name="setUp" is-config="true" duration-ms="18780" started-at="2020-10-30T22:20:38Z" finished-at="2020-10-30T22:20:57Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method status="PASS" signature="startDriver()[pri:0, instance:TestCases.Amazon@2781e022]" name="startDriver" is-config="true" duration-ms="1853" started-at="2020-10-30T22:20:57Z" depends-on-methods="framework.BaseTestCase.setUp" finished-at="2020-10-30T22:20:58Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- startDriver -->
        <test-method status="PASS" signature="beforeMethod(java.lang.reflect.Method)[pri:0, instance:TestCases.Amazon@2781e022]" name="beforeMethod" is-config="true" duration-ms="233" started-at="2020-10-30T22:20:58Z" finished-at="2020-10-30T22:20:59Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[public void TestCases.Amazon.test() throws java.lang.Exception]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeMethod -->
        <test-method status="FAIL" signature="test()[pri:0, instance:TestCases.Amazon@2781e022]" name="test" duration-ms="121593" started-at="2020-10-30T22:20:59Z" finished-at="2020-10-30T22:23:00Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [some text] but found [Urban Ladder Zephyr 65" TV Unit (Finish : Mahogany)]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [some text] but found [Urban Ladder Zephyr 65" TV Unit (Finish : Mahogany)]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:494)
	at org.testng.Assert.assertEquals(Assert.java:123)
	at org.testng.Assert.assertEquals(Assert.java:176)
	at org.testng.Assert.assertEquals(Assert.java:186)
	at framework.NativeDriver.assertEqual(NativeDriver.java:270)
	at TestCases.Amazon.test(Amazon.java:38)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- test -->
        <test-method status="PASS" signature="afterMethod(org.testng.ITestResult)[pri:0, instance:TestCases.Amazon@2781e022]" name="afterMethod" is-config="true" duration-ms="798" started-at="2020-10-30T22:23:00Z" finished-at="2020-10-30T22:23:01Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=test status=FAILURE method=Amazon.test()[pri:0, instance:TestCases.Amazon@2781e022] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterMethod -->
        <test-method status="PASS" signature="tearDown()[pri:0, instance:TestCases.Amazon@2781e022]" name="tearDown" is-config="true" duration-ms="2542" started-at="2020-10-30T22:23:01Z" finished-at="2020-10-30T22:23:04Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method status="PASS" signature="afterSuite()[pri:0, instance:TestCases.Amazon@2781e022]" name="afterSuite" is-config="true" duration-ms="111" started-at="2020-10-30T22:23:04Z" finished-at="2020-10-30T22:23:04Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterSuite -->
      </class> <!-- TestCases.Amazon -->
    </test> <!-- Test -->
  </suite> <!-- Suite -->
</testng-results>
